services:
  bytebank-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BYTEBANK_WEB_AUTH_DOMAIN: http://bytebank-web-auth-app:3001
    container_name: bytebank-web-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - BYTEBANK_WEB_AUTH_DOMAIN=http://bytebank-web-auth-app:3001
    restart: unless-stopped
    networks:
      - bytebank-network
    depends_on:
      - bytebank-web-auth

  bytebank-web-auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: bytebank-web-auth-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    networks:
      - bytebank-network

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    container_name: bytebank-storybook
    ports:
      - "6006:6006"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - bytebank-network

networks:
  bytebank-network:
    driver: bridge
